name: API CI

on:
  push:
    branches:
      - "main"
    paths:
      - "services/backend/**"
      - ".github/workflows/build-api.yml"

env:
  IMAGE_NAME: expense-tracker-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/backend
          file: ./services/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Log out from Docker Hub
        run: docker logout
